-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 23:20:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webvillas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webvillas` ;

-- -----------------------------------------------------
-- Schema webvillas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webvillas` DEFAULT CHARACTER SET utf8 ;
USE `webvillas` ;

-- -----------------------------------------------------
-- Table `webvillas`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webvillas`.`account` ;

CREATE TABLE IF NOT EXISTS `webvillas`.`account` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) BINARY NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `code` CHAR(5) NOT NULL,
  `activate` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webvillas`.`villa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webvillas`.`villa` ;

CREATE TABLE IF NOT EXISTS `webvillas`.`villa` (
  `title` VARCHAR(50) NOT NULL,
  `area` VARCHAR(200) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `people` SMALLINT NOT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `rating` ENUM('1', '2', '3') NOT NULL,
  `pool` TINYINT(1) NULL DEFAULT 0,
  `gym` TINYINT(1) NULL DEFAULT 0,
  `parking` TINYINT(1) NULL DEFAULT 0,
  `sauna` TINYINT(1) NULL DEFAULT 0,
  `usernamefk` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`usernamefk` ASC) VISIBLE,
  PRIMARY KEY (`title`),
  CONSTRAINT `fk_villa_account`
    FOREIGN KEY (`usernamefk`)
    REFERENCES `webvillas`.`account` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webvillas`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webvillas`.`photo` ;

CREATE TABLE IF NOT EXISTS `webvillas`.`photo` (
  `namephoto` VARCHAR(50) NOT NULL,
  `alt` VARCHAR(80) NULL,
  `villa_title` VARCHAR(50) NOT NULL,
  `username_fk` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`namephoto`),
  INDEX `fk_photo_villa1_idx` (`villa_title` ASC) VISIBLE,
  INDEX `fk_photo_account1_idx` (`username_fk` ASC) VISIBLE,
  CONSTRAINT `fk_photo_villa1`
    FOREIGN KEY (`villa_title`)
    REFERENCES `webvillas`.`villa` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_account1`
    FOREIGN KEY (`username_fk`)
    REFERENCES `webvillas`.`account` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
